version: "3"
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=urlshortener
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: bash -c "./start.sh"
    ports:
      - 8081:8080
    links:
      - db
